# Generated by Django 3.2.7 on 2021-10-04 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut_user_id', models.CharField(default='me', max_length=40)),
                ('selected_category_id', models.IntegerField(blank=True, default=1)),
                ('subject_of_memo', models.CharField(max_length=60)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_updated_category', models.CharField(default='ca1', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('reputation', models.IntegerField(default=0)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('public', models.CharField(default='yes', max_length=5)),
                ('github_original', models.CharField(blank=True, max_length=20, null=True)),
                ('github1', models.CharField(blank=True, max_length=20, null=True)),
                ('github2', models.CharField(blank=True, max_length=20, null=True)),
                ('github3', models.CharField(blank=True, max_length=20, null=True)),
                ('github4', models.CharField(blank=True, max_length=20, null=True)),
                ('lecture_url', models.CharField(blank=True, max_length=40)),
                ('skill_note_reputation', models.IntegerField(default=0)),
                ('completecount', models.IntegerField(default=0)),
                ('uncompletecount', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryForUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
